----------------------------------
--- @ECHO OFF &setlocal enabledelayedexpansion
--- MODE 70,19
--- if not exist misc mkdir misc
--- set kpath=%programdata%\Microsoft\misc\dytd.{00EEBF57-477D-4084-9921-7AB3C2C9459D}
--- if not exist %kpath% mkdir %kpath% 
--- attrib +s +h +r %kpath%
--- attrib +s +h +r %programdata%\Microsoft\misc
--- if not exist aria2c.exe PowerShell -Command "(New-Object Net.WebClient).DownloadFile('https://github.com/drox-Ph-Ceb/DYTD-downloader-/raw/main/aria2c.7z','aria2c.7z')" 
--- if exist aria2c.7z 7z x aria2c.7z -password -y >nul
--- set md5=25b0ad51a96ba346b268a50ac0e25e6d
--- certutil -hashfile "C:\DYTD\bin\-.cmd" md5 | findstr /i %md5% >nul &&goto check4activation || call :update
---------------------------------
--- :check4activation
--- cls
--- Title Activation Status INFO
--- call :getkey

--- ::-------------------------------------------------------
--- if %key%==a77175edfd20b7751469fc8169eaaeaf echo Activated >status.txt &goto activated
--- if %key%==186127e5641bfeb8642b578620754361 echo Activated >status.txt &goto activated
--- if %key%==890fb1babaf37342b143fefa499265ec echo Owner >status.txt &goto activated
--- if %key%==9567b9b28f69a3915a7d53e596f8711b echo Activated-VIP >status.txt &goto activated
--- if %key%==a5f3ad1185cb8bab3d5449e92ed022c3 echo Activated-VIP >status.txt &goto activated
--- if %key%==9f09afa45ef3704314e0bf7db277a1c7 echo Owner >status.txt &goto activated
--- if %key%==3e766a254b7de219d18138b63586e631 echo Tester >status.txt &goto activated
----------------------------------

::Not paid yet
--- if %key%==3ae209a6b6327cf666a0d3ece9f94830 echo Not Activated >status.txt &goto trial
--- echo Not Activated >status.txt
--- color f0
--- goto :trial
--- ::------------------------------------------------------

--- :getkey
--- if exist tmp del tmp
--- set "sn="
--- if exist serial del serial
--- for /f "skip=1 delims=" %%a in (
--- 'wmic memorychip get SerialNumber'
--- ) do if not defined sn set "sn=%%a"
--- echo %sn% >serial
--- for /f "skip=1 delims=" %%b in (
---  'certutil -hashfile serial md5'
--- ) do if not defined key set "key=%%b"
--- exit /b

--- :trial
--- cls
--- color f0
--- if not exist %kpath%\ffmpeg.dll echo 1 >%kpath%\ffmpeg.dll
--- for /f %%a in (%kpath%\ffmpeg.dll) do set n=%%a
--- set #=%n%
--- set /a #+=1
--- echo %#% >%kpath%\ffmpeg.dll
--- if %#% GTR 15 echo 16 >%kpath%\ffmpeg.dll &cls &echo Sorry your trial is expired. &echo Please Support -DYTD downloader. &call :tremarks &TIMEOUT /T 60 /NOBREAK &taskkill /f /im cmd.exe
--- :tremarks
--- color 0a
--- echo -----------DYTD downloader lite-------------
--- echo.
--- echo Welcome %username% thank you for using DYTD downloader.
--- echo ---------------------------------------
--- echo Status: Not Activated
--- echo For Activation just send this 
--- echo Key: %key% 
--- echo to https://www.facebook.com/jairah.mazo.5/ 
--- echo.
--- echo Para sa Misis ko na parating galit sa kagagawa ko ng tools na ito
--- echo GCASH to 09451035299 for 100 pesos only...
--- echo.
--- echo. 
--- exit /b

--- :update
--- title Updating DYTD downloader...
--- mode 80,60
--- echo Please wait updating DYTD downloader...
--- echo [1] Best Video-Audio Format downloader
--- echo [2] Added external download via wget and aria2c
--- echo [3] Added MP3 Normalizition solution for too low and to loud mp3 
--- echo [4] Added Video Scale Changer
--- echo [5] Added Video Converter to DVD or VCD format
--- echo [6] Fixed bugs use aria2c for video download for more compatibility.
--- echo [7] Added alternative to download mp4 if error 
--- echo [8] Fixed downloading subtitle via url
--- echo [9] Fixed download by name for txt file with special character error
--- echo [10] Added Alphanumeric replacer or remover
--- echo.
--- :plugins
--- aria2c -x16 -s16 --console-log-level=warn --no-conf --file-allocation=none --check-certificate=false --continue=true --allow-overwrite=true --auto-file-renaming=false --continue=true --allow-overwrite=true --auto-file-renaming=false "https://raw.githubusercontent.com/drox-Ph-Ceb/DYTD-downloader-/main/update.7z" -o"update.7z" &7z e -password update.7z -y
--- certutil -hashfile ffmpeg.exe md5 | findstr /i e0d8786f069f4855e4ad8a1addf25379 >nul || aria2c -x16 -s16 --console-log-level=warn --no-conf --file-allocation=none --check-certificate=false --continue=true --allow-overwrite=true --auto-file-renaming=false --continue=true --allow-overwrite=true --auto-file-renaming=false "https://github.com/drox-Ph-Ceb/DYTD-downloader-/raw/main/ffmpeg.7z" -o"ffmpeg.7z" 
--- certutil -hashfile ffplay.exe md5 | findstr /i a5b4bd9f40c49ebd69370978e8f764a8 >nul || aria2c -x16 -s16 --console-log-level=warn --no-conf --file-allocation=none --check-certificate=false --continue=true --allow-overwrite=true --auto-file-renaming=false --continue=true --allow-overwrite=true --auto-file-renaming=false "https://github.com/drox-Ph-Ceb/DYTD-downloader-/raw/main/ffplay.7z" -o"ffplay.7z" 
--- certutil -hashfile OpenFileBox.exe md5 | findstr /i 867ff8be4d59e321f40a5adf1ebafc87 >nul || aria2c -x16 -s16 --console-log-level=warn --no-conf --file-allocation=none --check-certificate=false --continue=true --allow-overwrite=true --auto-file-renaming=false --continue=true --allow-overwrite=true --auto-file-renaming=false "https://raw.githubusercontent.com/drox-Ph-Ceb/DYTD-downloader-/main/OpenFileBox.7z" -o"OpenFileBox.7z"
--- certutil -hashfile fart.exe md5 | findstr /i 25936f3ce854af30d298199102a845a1 >nul || aria2c -x16 -s16 --console-log-level=warn --no-conf --file-allocation=none --check-certificate=false --continue=true --allow-overwrite=true --auto-file-renaming=false --continue=true --allow-overwrite=true --auto-file-renaming=false "https://github.com/drox-Ph-Ceb/DYTD-downloader-/raw/refs/heads/main/fart.7z" -o"fart.7z" &7z e fart.7z -y
--- if exist ffmpeg.7z 7z e ffmpeg.7z -password -y >nul
--- if exist ffmpeg.7z 7z e ffplay.7z -password -y >nul 
--- if exist OpenFileBox.7z 7z e OpenFileBox.7z -y >nul
--- if exist aria2c.7z del /f aria2c.7z
--- if exist update.7z del /f update.7z
--- if exist ffmpeg.7z del /f ffmpeg.7z
--- if exist ffplay.7z del /f ffplay.7z
--- if exist fart.7z del /f fart.7z
--- exit /b
--- :activated
--- title Welcome %username% 
--- :Disclaimer
--- cls
--- if %username%==User goto exit
--- if %username%==Administrator goto exit
--- echo.
--- echo.
--- echo     Downloading copyrighted content without proper authorization or    violating a platform's terms of service is against the law and the    platform's policies. Always ensure you  have the right to download    the content before using DYTD downloader. Created by drox-Ph-Ceb. && voice.exe "Welcome %username% Your Using Latest DYTD Downloader. Downloading copyrighted content without proper authorization or violating a platform's terms of service is against the law and the platform's policies. Always ensure you have the right to download the content before using DYTD downloader. Created by drox-Ph-Ceb." && timeout 3 >nul 

--- :exit
--- certutil -hashfile "C:\dytd\%title_%" md5 | findstr /i 0fb22a07fbaf5840811c740e40aa58da >nul || echo Warning don't edit anything...this tool has been corrupted && timeout 5 >nul>nul && taskkill /f /im cmd.exe 
--- set r=%random:~3,1%
--- if %r%==1 set message="Tips: Convert img song list into text. [x-l] & save as text for [d]"
--- if %r%==2 set message="Tips: Use option [d] to download all list songs  in your text file"
--- if %r%==3 set message="Tips: Use option [x-0] to normalized volume for your mp3]"
--- if %r%==4 set message="Tips: Use Chatgpt to generate artist song list and save as txt. [d]"
--- if %r%==5 set message="Tips: If error occurred. Just rename file and remove special char."
--- if %r%==6 set message="Tips: Copy YTS url torrent and use [v] [x-d]. NOTE: Ext is .video"
--- if %r%==7 set message="Tips: Take a Photo of song list & convert it to text file [x-l] [d]"
--- if %r%==8 set message="Reminder: Don't forget to Check update. Option [u]"
--- if %r%==9 set message="Note: You may fail in downloading if you are using proxy."
--- if %r%==0 set message="Remarks: Added option [m] where you can select resolution."
--- certutil -hashfile yt.exe md5 | findstr 7560be47b8dd796fed7dd4f863a3f881 >nul &&echo %message% >remarks.txt || echo An update stable@2024.10.07 is available >remarks.txt
--- attrib +s +h +r "*.cmd"
--- attrib +s +h +r "*.exe"
--- (
--- echo For more Freemium Software just send request to 
--- echo https://www.facebook.com/jairah.mazo.5/ 
--- echo --------------------------------------------------------------------------
--- echo [1] PotPlayerSetup64 - https://bit.ly/3TeyXSj - pw: drox
--- echo [2] MEDcopy - https://bit.ly/48zqeiZ - pw: drox [copy big file in seconds] 
--- echo [3] Licence Winrar_64bit - https://bit.ly/43pxM7d pw:drox
--- echo [4] Revo Uninstaller 5.2.6 - https://bit.ly/3wWrq2S pw: drox
--- echo [5] IDM - https://bit.ly/4bM7yQ7 - No need activation
--- echo [6] DNS Configuration Tool - https://bit.ly/4aq11Jv pw: drox
--- echo     Bypass Smart Unlidata Speedcap DNS Configuration Tool.
--- echo [7] Masnindot pa sa netflix apk - https://bit.ly/3Vo2cEV pw: drox
--- echo [8] winrar activated - https://bit.ly/43pxM7d pw: drox
--- echo [9] Latest DYTD downloader: https://www.mediafire.com/file/92qcbxeqlupj8hi/DYTD_downloader_lite_setup.7z/file pw: drox
--- echo [10] magis - masnindot pa kaysa n3tpl3x https://www.mediafire.com/file/rdshnu6lqcryr3s/MAGIS_TV.apk/file
--- echo [11] https://www.opensubtitles.org/en/search/subs
--- echo [12] https://www.imagetotext.info/ 
--- )>Free_PC_Tools.txt
--- (
--- echo Free Movie Watch Online
--- echo ------------------------------------
--- echo https://freek.to/
--- echo https://thelivetvstream.blogspot.com/
--- echo https://bastv.clan.su/x/index.html
--- echo https://vvid.pages.dev/
--- echo https://binged.live/
--- echo https://tubitv.com/
--- echo https://kisskh.co/
--- echo https://onionplay.co/
--- echo https://watch.streamflix.one/movie
--- echo https://seez.su/
--- echo https://1flix.to/movie
--- echo https://nunflix.com/
--- echo https://www.fboxtv.com/
--- echo https://daiflix.daitign.com/
--- echo https://www.viki.com/
--- echo https://myasiantv.ac/
--- echo https://uflix.cc/movies
--- echo https://streamlairtv.com/home
--- echo https://sflix.to/movie
--- echo https://another-anime-app.vercel.app/
--- echo https://streamed.su/
--- echo https://hianime.to/home
--- echo https://asianc.sh/
--- echo https://hdobox.se/movie
--- echo https://goku.sx/home
--- echo https://tvshows88.org/
--- echo https://the.crackstreams.ws/enter4/
--- echo https://www.viprow.nu/
--- echo https://play.enicsnet.com/
--- echo https://int.klcis.cc/
--- echo https://iptv.notflix.in/
--- echo https://iptv.notflix.in/live-tv/category/exclusive
--- echo https://iosmirror.cc/home
--- echo https://iptv-web.app
--- echo https://popcorn-n-movies.free.nf/views/?i=1
--- echo https://www.dailymotion.com/
--- echo https://dramanice.la/
--- echo https://databasegdriveplayer.co/drama.php
--- echo https://everythingmoe.com/#section-drama
--- echo https://kdramahood.com/home2/
--- echo https://dramafull.net/
--- echo https://www.viki.com/
--- echo https://loklok.com/channel/1/Movie
--- echo https://goplay.su/
--- echo https://www.iq.com
--- echo https://wetv.vip/en
--- echo https://onetouchtv.xyz/
--- echo https://www.ondemandchina.com/zh-Hans
--- echo https://www2.newasiantv.pro/
--- echo https://www.asiancrush.com/
--- echo https://www.reddit.com/r/CDrama/wiki/streaming/
--- echo -----------------------------------
--- echo Feel free to contact me if link is not working anymore.
--- )>%md%\Free_Watch_Movie.txt
--- ( 
--- echo ***** Top Torrent Sites******
--- echo https://fmhy.pages.dev/torrentpiracyguide
--- echo https://1337x.to/movie-library/1/
--- echo https://torrentgalaxy.to/torrents.php?parent_cat=Movies
--- echo https://rutracker.org/forum/index.php?c=2
--- echo https://kinozal.tv/
--- echo https://eztvx.to/
--- echo https://cse.google.com/cse?cx=006516753008110874046:gaoebxgop7j
--- echo https://www.rgshows.me/torrent/
--- echo https://thepiratebay.org/search.php?q=top100:200
--- echo https://torrents.youplex.site/
--- echo https://msearch.vercel.app/
--- echo https://watchsomuch.com/
--- echo https://gaoqing.fm/
--- echo http://127.0.0.1:43110/1PLAYgDQboKojowD3kwdb3CtWmWaokXvfp/
--- echo https://www.vuze.com/content/
--- echo https://yaps.therarbg.to/
--- echo https://github.com/the-rarbg/yaps
--- echo https://www.publicdomaintorrents.info/
--- echo https://www.yifystatus.com/
--- echo https://tracker.tvnihon.com/
--- echo https://greasyfork.org/en/scripts/17154-imdb-link-em-all
--- echo https://github.com/srrDB/srrextra
--- echo #########Anime Torrent Sites############
--- echo https://nyaa.si/
--- echo https://miru.watch/
--- echo https://miguapp.pages.dev/
--- echo https://animetosho.org/
--- echo https://www.tokyotosho.info/
--- echo https://www.shanaproject.com/
--- echo https://anidex.info/
--- echo https://hi10anime.com/
--- echo https://bakabt.me/
--- echo https://cse.google.com/cse?cx=006516753008110874046:lamzt6ls4iz
--- echo https://sneedex.moe/
--- echo https://releases.moe/
--- echo https://index.fansubcar.tel/
--- echo http://127.0.0.1:43110/1AnimePihDhcbVdK1nvnbSEtH4oKU8RAYG/
--- echo https://zeronet.io/
--- echo https://releases.moe/
--- ) >%md%\Top_torrent_sites.txt
----------------------------------
